# Generated by Django 3.1.5 on 2021-02-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat_class',
            fields=[
                ('chat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('chat_history', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='chat_histor',
            fields=[
                ('chat_history_id', models.IntegerField(primary_key=True, serialize=False)),
                ('chat_history_time', models.TextField()),
                ('chat_history_discription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='group_chat',
            fields=[
                ('group_chat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_chat_name', models.CharField(max_length=30)),
                ('group_chat_history', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='permissions',
            fields=[
                ('permissions_id', models.IntegerField(primary_key=True, serialize=False)),
                ('permissions_role_id', models.IntegerField()),
                ('permissions_title', models.TextField()),
                ('permissions_module', models.TextField()),
                ('permissions_description', models.TextField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=15)),
                ('role_description', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_class',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_role_id', models.IntegerField()),
                ('user_email', models.TextField()),
                ('user_don', models.DateTimeField()),
                ('user_addresses', models.TextField(max_length=255)),
            ],
        ),
    ]
